@extends('web.app')

@section('content')
    <!-- Start Terms & Conditions -->
    <section class="section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="card shadow border-0 rounded">
                        <div class="card-body">
                            <br>
                            <h5 class="card-title">PLEASE READ THESE TERMS CAREFULLY BEFORE USING THIS SITE:</h5>
                            <p class="text-muted">This web site (www.PurnPay.com) is published and maintained by
                                PurnPay , a professionally managed company, headquartered in Shop No.109, Farm Complex
                                Near Moomal Photostate Sriganga Nagar, Suratgarh, Rajasthan, India, 335804. PurnPay
                                provides services to you subject to the following conditions. If you visit or do any
                                transaction within this website, you accept these conditions. Please read them
                                carefully.</p>

                            <p class="text-muted">THIS TERMS AND CONDITIONS IS AN ELECTRONIC RECORD IN THE FORM OF AN
                                ELECTRONIC CONTRACT FORMED UNDER THE INFORMATION TECHNOLOGY ACT, 2000 AND THE RULES MADE
                                THEREUNDER AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC DOCUMENTS / RECORDS IN
                                VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000.<br>
                                THIS DOCUMENT IS PUBLISHED AND SHALL BE CONSTRUED IN ACCORDANCE WITH THE PROVISIONS OF
                                THE INFORMATION TECHNOLOGY (REASONABLE SECURITY PRACTICES AND PROCEDURES AND SENSITIVE
                                PERSONAL DATA OF INFORMATION) RULES, 2011 UNDER INFORMATION TECHNOLOGY ACT, 2000; THAT
                                REQUIRE PUBLISHING OF THE PRIVACY POLICY FOR COLLECTION, USE, STORAGE AND TRANSFER OF
                                SENSITIVE PERSONAL DATA OR INFORMATION.<br>
                                PLEASE READ THIS TERMS AND CONDITIONS CAREFULLY BEFOUR YOU CLICK ON “I AGREED”. BY USING
                                THE WEBSITE, YOU INDICATE THAT YOU UNDERSTAND, AGREE AND CONSENT TO THIS TERMS AND
                                CONDITIONS. IF YOU DO NOT AGREE WITH THE TERMS OF THIS WEBSITE, PLEASE DO NOT USE THIS
                                WEBSITE. YOU HEREBY PROVIDE YOUR UNCONDITIONAL CONSENT OR TERMS AND CONDITIONS S TO
                                “PurnPay .” AS PROVIDED UNDER SECTION 43A AND SECTION 72A OF INFORMATION TECHNOLOGY ACT,
                                2000.
                            </p>

                            <h5 class="card-title">SOFTWARE:</h5>
                            <p class="text-muted">Any software, including any files, usages generated by the software,
                                code, and data accompanying the software (collectively, "Software"), used or accessible
                                through this Site may be used by you solely for accessing and using this Site for
                                purposes expressly stated on the Site, provided that such uses are not competitive with
                                or derogatory to PurnPay . PurnPay retains full and complete title to and all
                                intellectual property rights in the Software. You agree not to copy, distribute, sell,
                                modify, decompile, reverse engineer, disassemble or create derivative works from any
                                Software.</p>


                            <h5 class="card-title">USER CONDUCT:</h5>
                            <p class="text-muted">In using this Site, you agree:</p>
                            <ul class="list-unstyled text-muted">
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Not to disrupt or
                                    interfere with the security of, or otherwise abuse, the Site, or any services,
                                    system resources, accounts, servers or networks connected to or accessible through
                                    the Site or affiliated or linked Web sites;</li>

                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Not to disrupt or
                                    interfere with any other user's enjoyment of the Site or affiliated or linked Web
                                    sites;</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Not to upload, post, or
                                    otherwise transmit through or on this Site any viruses or other harmful, disruptive
                                    or destructive files;</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Not to use or attempt
                                    to use another's account, service or system without authorization from PurnPay , or
                                    create or use a false identity on this Site;</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Not to transmit through
                                    or on this Site spam, chain letters, junk mail or any other type of unsolicited mass
                                    email to people or entities who have not agreed to be part of such mailings;</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Not to share, your
                                    username and password to others either on or off the Site;</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Not to attempt to
                                    obtain unauthorized access to the Site or portions of the Site which are restricted
                                    from PurnPay access; and,</li>

                            </ul>

                            <p class="text-muted">In addition, you agree that you are solely responsible for actions
                                and communications undertaken or transmitted under your account, and that you will
                                comply with all applicable local, state, national and international laws and
                                regulations, including India, that relate to your use of or activities on this Site.
                                This Site is controlled and operated in the India. If you are in a jurisdiction which
                                restricts you from accessing this Site, do not access or use this Site. PurnPay makes no
                                representation that the Site is appropriate or available for use outside the India.</p>

                            <h5>PRIVACY POLICY:</h5>

                            <p class="text-muted">You acknowledged PurnPay may use the data collected in the course of
                                our relationship for the purposes identified in our Privacy Policy, which is
                                incorporated by reference as if fully set forth in these Terms of Use.</p>

                            <h5>INFORMATION SECURITY</h5>

                            <p class="text-muted">For Your Personal Information we use proper security measures and
                                apply ISO 270001: 2013 Standard which assured you we follow the entire standard and it
                                gives you assurance that we keep your information safe and secure.</p>

                            <h5>LINKS AND THIRD-PARTY CONTENT</h5>

                            <p class="text-muted">
                                This Site may from time to time contain links to other Web sites. These links are
                                provided as a convenience and do not constitute an endorsement, sponsorship or
                                recommendation by PurnPay , of or responsibility for the linked Web sites or any
                                content, services or products available on or through such sites.</p>

                            <h5>Links from Other Web Sites</h5>

                            <p class="text-muted">All links to this Site must be approved in writing by PurnPay ,
                                except that PurnPay , consents to links in which:</p>

                            <ul class="list-unstyled text-muted">
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>The link is a text-only
                                    link containing only the title of the home page of this Site,</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>The link "points" only
                                    to the home pages of the Site and not to deeper pages,</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>The link, when
                                    activated by a user, displays this home page of the Site full-screen and not within
                                    a "frame" on the linked Web site, and</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>The appearance,
                                    position, and other aspects of the link do not.</li>
                            </ul>

                            <h5>THIRD PARTY CONTENT</h5>

                            <p class="text-muted">This Site may from time to time contain material, data or information
                                provided, posted or offered by third parties, including but not limited to
                                advertisements or postings in online community discussions. You agree that neither
                                PurnPay , nor its affiliates shall have any liability whatsoever to you for any such
                                third-party material, data or information.</p>

                            <h5>THIRD PARTY CONTENT</h5>

                            <p class="text-muted">This site and the content available through it are provided on an "as
                                is" and "as available" basis. you expressly agree that use of this site and/or its
                                content is at your sole risk. to the fullest extent permissible pursuant to applicable
                                law, PurnPay , and its affiliates disclaim all warranties of any kind, whether express
                                or implied, including without limitation any warranty of merchantability, fitness for a
                                particular purpose or non-infringement. you expressly agree that use of this site,
                                including all content, data or software distributed by, downloaded or accessed from or
                                through the site, is at your sole risk. you understand and agree that you will be solely
                                responsible for any PurnPay . to your business, your computer system or loss of data
                                that results from the download of such content, data and/or software or equipmentyou
                                acknowledge PurnPay , that does not control information, products or services offered by
                                third parties through the site. except as otherwise agreed in writing, and its
                                affiliates assume no responsibility for and make no warranty or representation as to the
                                accuracy, currency, completeness, reliability or usefulness of any advice, opinion,
                                statement or other content or of any products or services distributed or made available
                                by third parties through the site. does not make any warranty that this site or its
                                content will meet your requirements, or that this site or its content will be
                                uninterrupted, timely, secure, or error free, or that defects, if any, will be
                                corrected. nor does makes any warranty as to the results that may be obtained from use
                                of this site or its content or as to the accuracy, completeness or reliability of any
                                information obtained through use of this site.</p>

                            <p class="text-muted">PurnPay , ASSUMES NO RESPONSIBILITY FOR ANY LOSS SUFFERED BY A USER,
                                INCLUDING, BUT NOT LIMITED TO, LOSS OF DATA FROM DELAYS, NONDELIVERIES OF CONTENT OR
                                EMAIL, ERRORS, SYSTEM DOWN TIME, MISDELIVERIES OF CONTENT OR EMAIL, NETWORK OR SYSTEM
                                OUT PurnPay ’S, FILE CORRUPTION, OR SERVICE INTERRUPTIONS CAUSED BY THE NEGLIGNCE
                                PurnPay OF PurnPay . , ITS AFFILIATES, ITS LICENSORS, OR A USER'S OWN ERRORS AND/OR
                                OMISSIONS EXCEPT AS SPECIFICALLY PROVIDED HEREIN, PurnPay DISCLAIMS ANY WARRANTY OR
                                REPRESENTATION THAT CONFIDENTIALITY OF INFORMATION TRANSMITTED THROUGH THE SITE WILL BE
                                MAINTAINED.</p>

                            <h5>LIMITATION OF LIABILITY</h5>

                            <p class="text-muted">UNDER NO CIRCUMSTANCES, INCLUDING, WITHOUT LIMITATION, PurnPay SHALL
                                OR ITS PARENTS, SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, OR SUPPLIERS
                                BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING
                                FROM OR IN CONNECTION WITH THE USE OF OR THE INABILITY TO USE THIS SITE OR ANY CONTENT
                                CONTAINED ON THE SITE, OR RESULTING FROM UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR
                                TRANSMISSIONS OR DATA, OR OTHER INFORMATION THAT IS SENT OR RECEIVED OR NOT SENT OR
                                RECEIVED, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, USE, DATA OR OTHER
                                INTANGIBLES, EVEN IF PurnPay HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES <br>
                                THE PARTIES ACKNOWLED THAT THIS IS A REASONABLE ALLOCATION OF RISK. SOME JURISDICTIONS
                                DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL
                                DAMAGES, SO SOME OF THE ABOVE MAY NOT APPLY TO YOU.
                            </p>

                            <h5>PurnPay APPLICABLE LAW.</h5>

                            <p class="text-muted">These Terms of Use shall be governed by and construed in accordance
                                with the laws of India. You agree to submit to the personal and exclusive jurisdiction
                                of the Indian courts located within Navi Mumbai, India. These terms constitute the
                                entire Terms and conditions between you and PurnPay , governing your use of the Site.
                                Should any provision in these terms be found invalid or unenforceable for any reason,
                                then that provision shall be deemed severable from the terms and shall not affect the
                                validity or enforceability of the remaining provisions. You agree that any claim arising
                                out of or related to the terms or your use of the Site must be filed within one year
                                after it arose or be permanently barred.</p>

                            <h5>ELECTRONIC COMMUNICATIONS</h5>

                            <p class="text-muted">When you visit PurnPay or send e-mails to us, you are communicating
                                with us electronically. You consent to receive communications from us electronically. We
                                will communicate with you by e-mail or by posting notices on this site. You agree that
                                all Terms and conditions s, notices, disclosures and other communications that we
                                provide to you electronically satisfy any legal requirement that such communications be
                                in writing.</p>

                            <h5>COPYRIGHT</h5>

                            <p class="text-muted">All content included on this site, such as text, graphics, logos,
                                button icons, images, audio clips, digital downloads, data compilations, software,
                                hardware’s and Equipment’s is the property of PurnPay or its content suppliers and
                                protected by international copyright laws. The compilation of all content on this site
                                is the exclusive property of PurnPay , with copyright authorship for this collection by
                                PurnPay and protected by international copyright laws.</p>

                            <h5>TRADE MARKS</h5>

                            <p class="text-muted">PurnPay trademarks and trade dress may not be used in connection with
                                any product or service that is not PurnPay , in any manner that is likely to cause
                                confusion among customers, or in any manner that disparages or discredits PurnPay . All
                                other trademarks not owned by PurnPay that appear on this site are the property of their
                                respective owners, who may or may not be affiliated with, connected to, or sponsored by
                                PurnPay or its subsidiaries.</p>

                            <h5>LICENSE AND SITE ACCESS</h5>

                            <p class="text-muted">PurnPay grants you a limited license to access and make personal use
                                of this site and not to download or modify it, or any portion of it, except with express
                                written consent of PurnPay . This license does not include any resale or commercial use
                                of this site or its contents: any collection and use of any product listings,
                                descriptions, or prices: any derivative use of this site or its contents: any
                                downloading or copying of account information for the benefit of another merchants or
                                Customers: or any use of data mining, robots, or similar data gathering and extraction
                                tools and malware or virus or penetration testing. This site or any portion of this site
                                may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited
                                for any commercial purpose without express written consent of PurnPay . You may not
                                frame or utilize framing techniques to enclose any trademark, logo, or other proprietary
                                information (including images, text, page layout, or form) of PurnPay and our associates
                                without express written consent. You may not use any Meta tags or any other "hidden
                                text" utilizing PurnPay or trademarks without the express written consent of PurnPay .
                                Any unauthorized use terminates the permission or license granted by PurnPay . You are
                                granted a limited, revocable, and nonexclusive right to create a hyperlink to the home
                                page of PurnPay so long as the link does not portray PurnPay , its associates, or their
                                products or services in a false, misleading, derogatory, or otherwise offensive matter.
                                You may not use any PurnPay logo or other proprietary graphic or trademark as part of
                                the link without express written permission.</p>

                            <h5>REVIEWS, COMMENTS, EMAILS, AND OTHER CONTENT</h5>

                            <p class="text-muted">Visitors may post reviews, comments, and other content, and submit
                                suggestions, ideas, comments, questions, or other information, so long as the content is
                                not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of
                                intellectual property rights, or otherwise injurious to third parties or objectionable
                                and does not consist of or contain software viruses, political campaigning, commercial
                                solicitation, chain letters, mass mailings, or any form of "spam." You may not use a
                                false e-mail address, impersonate any person or entity, or otherwise mislead as to the
                                origin of a card or other content. PurnPay reserves the right (but not the obligation)
                                to remove or edit such content but does not regularly review posted content. If you do
                                post content or submit material, and unless we indicate otherwise, you grant PurnPay and
                                its associates a nonexclusive, royalty-free, perpetual, irrevocable, and fully sub
                                licensable right to use, reproduce, modify, adapt, publish, translate, create derivative
                                works from, distribute, and display such content throughout the world in any media. You
                                grant PurnPay and its associates and sub licensees the right to use the name that you
                                submit in connection with such content, if they choose. You represent and warrant that
                                you own or otherwise control all of the rights to the content that you post, that the
                                content is accurate, that use of the content you supply does not violate this policy and
                                will not cause injury to any person or entity, and that you will indemnify PurnPay or
                                its associates for all claims resulting from content you supply. PurnPay has the right
                                but not the obligation to monitor and edit or remove any activity or content. PurnPay
                                takes no responsibility and assumes no liability for any content posted by you or any
                                third party.</p>

                            <h5>PRODUCT DESCRIPTIONS</h5>

                            <ul class="list-unstyled text-muted">
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Products Division</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Technology
                                    Services/Product development</li>
                                <li><i data-feather="arrow-right" class="fea icon-sm me-2"></i>Trading</li>
                            </ul>

                            <h5>RESPONSIBILITY FOR YOUR SITE</h5>

                            <p class="text-muted">You will be solely responsible for the development, operation, and
                                maintenance of your site and for all materials that appear on your site. For example,
                                you will be solely responsible for:
                                The technical operation of your site and all related equipment.
                                Ensuring the display of Special Links on your site does not violate any Terms and
                                conditions between you and any third party (including without limitation any
                                restrictions or requirements placed on you by a third party that hosts your site).
                                Creating and posting Product descriptions on your site and linking those descriptions to
                                the PurnPay . Site catalog </p>

                            <p class="text-muted">The accuracy and appropriateness of materials posted on your site
                                (including, among other things, all Product-related materials and any information you
                                include within or associate with Special Links) <br>
                                Ensuring that materials posted on your site do not violate or infringe upon the rights
                                of any third party (including, for example, copyrights, trademarks, privacy, or other
                                personal or proprietary rights)Ensuring that materials posted on your site are not
                                libelous or otherwise illegal
                                Ensuring that your site accurately and adequately discloses, either through a privacy
                                policy or otherwise, how you collect, use, store, and disclose data collected from
                                visitors, including, where applicable, that third parties (including advertisers) may
                                serve content and/or advertisements and collect information directly from visitors and
                                may place or recognize cookies on visitors' browsers. <br>
                                We disclaim all liability for these matters. Further, you will indemnify and hold us
                                harmless from all claims, PurnPay , and expenses (including, without limitation,
                                attorneys' fees) relating to the development, operation, maintenance, and contents of
                                your site. We also advise you to strictly abide by the terms narrated in Clause 1 above
                                of this terms and conditions and any non-observance of the terms therein shall determine
                                our association with immediate effect.
                            </p>
                            <h5>COMPLIANCE WITH LAWS</h5>
                            <p class="text-muted">As a condition to your participation in the Program, you agree that
                                while you are a Program participant you will comply with all laws, ordinances, rules,
                                regulations, orders, licenses, permits, judgments, decisions or other requirements of
                                any governmental authority that has jurisdiction over you, whether those laws, etc. are
                                now in effect or later come into effect during the time you are a Program participant.
                                Without limiting the foregoing obligation, you agree that as a condition of your
                                participation in the Program you will comply with all applicable laws of India that
                                govern marketing email and all other anti-spam laws.</p>

                            <h5>REFUND POLICY</h5>

                            <p class="text-muted">The refund amount in case of any cancellation will be refunded within
                                48 hours, in case of no show the refund will be processed only after we get refund from
                                the airlines, after deducting the airline cancellation charges and applicable service
                                charge. The amount will be refunded in the form of e-money (limit) in your portal, the
                                refund amount will not be deposited directly in your bank account, debit/credit card.
                            </p>

                            <h5>TERM OF THE TERMS AND CONDITIONS</h5>

                            <p class="text-muted">The term of this Terms and conditions will begin upon our acceptance
                                of your Program Application and will end when terminated by either party. Either you or
                                we may terminate this Terms and conditions at any time, with or without cause, by giving
                                the other party written notice of termination. Upon the termination of this Terms and
                                conditions for any reason, you will immediately cease use of, and remove from your site,
                                all links to the PurnPay . Site, and all of our trademarks, trade dress, and logos, and
                                all other materials provided by or on behalf of us to you pursuant hereto or in
                                connection with the Program. You are eligible to earn referral fees only on sales of
                                Qualifying Products that occur during the term, and referral fees earned through the
                                date of termination will remain payable only if the related orders are not canceled or
                                returned. We may withhold your final payment for a reasonable time to ensure that the
                                correct amount is paid. Effect of Termination: Upon termination of this Terms and
                                conditions by either side you will cease to be an affiliate and shall remove all links
                                to the PurnPay . site as detailed herein above and non-removal of links and use of all
                                or any of our trademark, trade dress, logos and price are treated as illegal crawling
                                and infringement PurnPay of our Trademark.</p>

                            <h5>MODIFICATION</h5>

                            <p class="text-muted">We may modify any of the terms and conditions contained in this Terms
                                and conditions, without prior notice at any time and in our sole discretion, by posting
                                a change PurnPay notice or a new Terms and conditions on the PurnPay , Site.
                                Modifications may include, for example, changes PurnPay in the scope of available
                                referral fees, referral fee schedules, payment procedures, and Program rules. If any
                                modification is unacceptable to you, your only recourse is to terminate this Terms and
                                conditions. Your continued participation in the program following our posting of a
                                change notice or new Terms and conditions on the PurnPay , site will constitute binding
                                acceptance of the change PurnPay .<br>
                                You and we are independent contractors, and nothing in this Terms and conditions will
                                create any partnership, joint venture, agency, franchise, sales representative, or
                                employment relationship between the parties. You will have no authority to make or
                                accept any offers or representations on our behalf. You will not make any statement,
                                whether on your site or otherwise, that reasonably would contradict anything in this
                                clause.
                            </p>

                            <h5>LIMITATION OF LIABILITY</h5>
                            <p class="text-muted">We will not be liable for indirect, special, or consequential damages
                                (or any loss of revenue, profits, or data) arising in connection with this Terms and
                                conditions or the Program, even if we have been advised of the possibility of such
                                damages. Further, our aggregate liability arising with respect to this Terms and
                                conditions and the Program will not exceed the total referral fees paid or payable to
                                you under this Terms and conditions.</p>

                            <h5>INDEPENDENT INVESTIGATION</h5>
                            <p class="text-muted">You acknowledge that you have read this Terms and conditions and
                                agree to all its terms and conditions. You understand that we may at any time (directly
                                or indirectly) solicit customer referrals on terms that may differ from those contained
                                in this Terms and conditions or operate web sites that are similar to or compete with
                                your web site. You have independently evaluated the desirability of participating in the
                                program and are not relying on any representation, guarantee, or statement other than as
                                set forth in this Terms and conditions.</p>

                            <h5>TERMS AND CONDITIONS CHANGE, PurnPay </h5>

                            <p class="text-muted">We may in our discretion change these Terms, PurnPay . Conditions of
                                Use and Privacy Notice, or any aspect of membership, without notice to you. If any
                                change to these terms is found invalid, void, or for any reason unenforceable, that
                                change is severable and does not affect the validity and enforceability of any remaining
                                changes or conditions. YOUR CONTINUED MEMBERSHIP AFTER WE CHANGE THESE TERMS CONSTITUTES
                                YOUR ACCEPTANCE OF THE CHANGES. IF YOU DO NOT AGREE TO ANY CHANGES, YOU MUST CANCEL YOUR
                                ORDER OR SERVICES.</p>

                            <h5>APPLICABLE LAW</h5>
                            <p class="text-muted">These Terms of Sale shall be governed in accordance with the laws of
                                India without reference to conflict of laws principles. You acknowledge that these Terms
                                of services and Sale are solely for Your benefit. It is not for the benefit of any other
                                person, except for Your successors and permitted assigns.</p>

                            <h5>SITE POLICIES, MODIFICATION, AND SEVERABILITY</h5>

                            <p class="text-muted">Please review our other policies, such as our “Privacy Policy” posted
                                on this site. These policies also govern your visit to PurnPay . We reserve the right to
                                make changes to our site, policies, and these Conditions of Use at any time. If any of
                                these conditions shall be deemed invalid, void, or for any reason unenforceable, that
                                condition shall be deemed severable and shall not affect the validity and enforceability
                                of any remaining condition.</p>

                            <h5>QUESTIONS</h5>

                            <p class="text-muted">Questions regarding our Conditions of Usage, Privacy Policy, or other
                                policy related material can be directed to our support staff by clicking on the "Contact
                                Us" link in the side menu. Or you can email us at: <a
                                    href="mailto:info@purnpay.com"><span>info@PurnPay.com</span></a>
                            </p>

                        </div>
                    </div>
                </div><!--end col-->
            </div><!--end row-->
        </div><!--end container-->
    </section><!--end section-->
    <!-- End Terms & Conditions -->
@endsection